### ISSUE TITLE
Unable to run Yarn start command

### ISSUE THREAD

**Issue by mevinbabuc** [zeemon/happyfeet#1]
```
module.js:472
    throw err;
    ^

Error: Cannot find module './lib/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mevinbabu/Gale/tasks/happyfeet/react-app/tools/clean.js:10:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/mevinbabu/Gale/tasks/happyfeet/react-app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mevinbabu/Gale/tasks/happyfeet/react-app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

I get module not found error when trying to run the project. I think `./lib/fs` file is missing in the code. 

I'm on node version 7.7.3 and npm version 4.1.2

**Comment by zeemon** [comment]
Hi Mevin,

Sorry for that. I used a starter kit
https://github.com/kriasoft/react-starter-kit for the project. Get started
documentation is at
https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md
.

The installation on my local had run pretty smoothly. However on the server
when i tried for yarn start i got the issue of ./lib/fs. Sorry to say i
ignored it since it worked on my local and i couldnt find the specified
file in my node modules. Could it perhaps be OS specific? I built mine on
ubuntu 14 locally and the server OS was ubuntu 16.

Am at work currently so cannot do anything about it. I will try a
re-install of my code at home and let you know by tomorrow morning if its
ok with you ?

Sorry for the inconvenience.
